baseurl = "https://bitsforeveryone.github.io"
DefaultContentLanguage = "en"
title = "BitsForEveryone"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
paginate = 5

[Params]
  subtitle = "ctf writeups and projects"
  logo = "img/bfe.png"
  favicon = "img/favicon.ico"
  dateFormat = "2 January, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "bfe"
  website = "bitsforeveryone.com"
  github = "bitsforeveryone"

[[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "writeup/"
    weight = 1

[[menu.main]]
    parent = "writeups"
    name = "all"
    url = "page/all"
    weight = 1

[[menu.main]]
    name   = "Projects"
    url    = "project/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 4

